name: Child

on:
  workflow_call:

jobs:
  start-child:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Run something"

  always-fail:
    runs-on: ubuntu-latest
    needs: [ start-child ]
    steps:
      - run: |
          echo "Fail"
          exit 1

  finish-child:
    runs-on: ubuntu-latest
    needs: [ always-fail ]
    if: ${{ always() }}
    steps:
      - run: |
          echo "Finished"
