name: TEST-PARENT

on:
  workflow_dispatch:

jobs:
  start-parent:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Run parent"

  call-child:
    name: child
    needs: [ start_pipeline ]
    uses: ./child.yml

  finish-parent:
    needs: [ call-child ]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Success: ", ${{ success() }}
          echo "Failure: ", ${{ failure() }}
