name: TEST-PARENT

on:
  workflow_dispatch:

env:
  cluster_id: ''

jobs:
  start-parent:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Run parent"

  write-env:
    runs-on: ubuntu-latest
    needs: [ start-parent ]
    steps:
      - run: |
          echo 'cluster_id=hello' | tee -a $GITHUB_ENV

  read-env:
    runs-on: ubuntu-latest
    needs: [ write-env ]
    steps:
      - run: |
          echo ${{ env.cluster_id }}

  call-remote:
    name: remote
    needs: [ start-parent ]
    uses: dbhao/github_action_test_2/.github/workflows/remote.yml@master

  call-child:
    name: child
    needs: [ start-parent ]
    uses: ./.github/workflows/child.yml

  finish-success:
    needs: [ call-child ]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - run: |
          echo "Success"

  finish-failure:
    needs:
      - call-child
      - call-remote
      - read-env
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: |
          echo "Failure"
