name: TEST-PARENT

on:
  workflow_dispatch:

jobs:
  start-parent:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Run parent"

  call-remote:
    name: remote
    needs: [ start-parent ]
    uses: dbhao/github_action_test_2/.github/workflows/remote.yml@master

  call-child:
    name: child
    needs: [ start-parent ]
    uses: ./.github/workflows/child.yml

  finish-success:
    needs: [ call-child ]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - run: |
          echo "Success"

  finish-failure:
    needs: [ call-child ]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - run: |
          echo "Failure"
