name: TEST-CI

on:
  workflow_dispatch:
    inputs:
      name:
        desc: 'Manual triggered by $GITHUB_ACTOR'
  schedule:
    - cron: '*/2 * * * *'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Run something"
        echo "Log level: ${{ github.event.inputs.name }}"

