name: TEST-CI

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: '30 * * * *'

env:
  TAG_FILTER: "v4."

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Run something"

  printEnv:
    runs-on: ubuntu-latest
    steps:
      - run: |
          export

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  matrix_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        parameter: [ setting_1, setting_2 ]
        testsuite:
          - name: suite1
            dir: >-
              subdir/suite1
            target: test
          - name: suite2
            dir: "subdir/suite3 subdir/suite3/abc subdir/suite3_1"
            target: test
          - name: suite3
            dir: subdir/suite3
            target: test
    steps:
      - name: run tests
        shell: bash
        run: |
          dirs="${{matrix.testsuite.dir}}"
          dirArray=($dirs)
          for dir in "${dirArray[@]}"; do
            echo "${dir}"
          done
