name: TEST-CI

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
  schedule:
    - cron: '*/2 * * * *'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Run something"
        echo "Name: ${{ github.event.inputs.name }}"
        echo "Home: ${{ github.event.inputs.home }}"

